logging:
  level:
    root: warn

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/springdb
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: dlsekdtlqdjrdnjs
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  data:
    mongodb:
      host: 34.64.151.162
      port: 27017
      database: parkingflex
      authentication-database: parkingflex
      username: parkingflex
      password: tkaqorclf
  profiles:
    active: local
#  messages:
#    always-use-message-format: false # Set whether to always apply the MessageFormat rules, parsing even messages without arguments.
#    basename: messages # Comma-separated list of basenames, each following the ResourceBundle convention.
#    cache-seconds: -1  # Loaded resource bundle files cache expiration, in seconds. When set to -1, bundles are cached forever.
#    encoding: UTF-8  # Message bundles encoding.
#    fallback-to-system-locale: true # Set whether to fall back to the system Locale if no files for a specific Locale have been found.


external:
  mqtt:
    urls: 192.168.0.203:3306, 192.168.0.250:3306

