logging:
  level:
    root: warn

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/springdb
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: dlsekdtlqdjrdnjs
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  data:
    mongodb:
      host: 34.64.151.162
      port: 27017
      database: parkingflex
      authentication-database: parkingflex
      username: parkingflex
      password: tkaqorclf
  profiles:
    active: local